POST http://localhost:8080/api/users
content-type:application/json

{
  "email": "user2@example.com"
}

###
GET http://localhost:8080/api/users

### Créer un nouveau client
POST http://localhost:8080/clients/register
Content-Type: application/json

{
  "prenom": "Jean",
  "nom": "Dupont",
  "email": "jean.dupont@example.com",
  "fonction": "CEO",
  "nomEntreprise": "Dupont Entreprises",
  "numEntreprise": "123456789",
  "formeJuridique": "SA",
  "adresseSiegeSocial": "123 Rue Principale, 1000 Bruxelles",
  "adresseSiteWeb": "https://dupont-entreprises.com",
  "codeNaceActivitePrincipale": "6201",
  "dernierChiffreDAffaire": 1500000.75,
  "estFranchise": false,
  "nbTravailleur": 50,
  "estDansUnLitige": false,
  "demandeDeLabel": true,
  "partenaire": "Banque Centrale",
  "commentaire": "Client VIP",
  "password": "password123"
}

### Créer un nouveau client (invalide)
POST http://localhost:8080/clients/register
Content-Type: application/json

{
  "prenom": "",
  "nom": "Dupont",
  "email": "jean.dupontexample.com",
  "fonction": "CEO",
  "nomEntreprise": "Dupont Entreprises",
  "numEntreprise": "123456789",
  "formeJuridique": "SA",
  "adresseSiegeSocial": "123 Rue Principale, 1000 Bruxelles",
  "adresseSiteWeb": "https://dupont-entreprises.com",
  "codeNaceActivitePrincipale": "6201",
  "dernierChiffreDAffaire": -1500000.75,
  "estFranchise": false,
  "nbTravailleur": -50,
  "estDansUnLitige": false,
  "demandeDeLabel": true,
  "partenaire": "Banque Centrale",
  "commentaire": "Client VIP",
  "mdp": "pass"
}

### connecter client (valide)
POST http://localhost:8080/clients/login
Content-Type: application/json

{
  "email": "sophie.martin@example.com",
  "password": "securePass2024!"
}

### connecter Consultant (valide)
POST http://localhost:8080/consultants/login
Content-Type: application/json

{
  "email": "simon.bosseler@vinci.be",
  "password": "password123"
}

### créer un questionnaire ESG pour un client
POST http://localhost:8080/questionnaires/create/questionnaireESG
Content-Type: application/json

{
  "idClient": "6751b25c0b15056747f31f26"
}

### Récupérer tous les clients
GET http://localhost:8080/clients/All


### Récupérer un seul client par son id
GET http://localhost:8080/questionnaires/6752e868faa3e31b8f1a4b45

### Valider un questionnaire ESG
PATCH http://localhost:8080/questionnaires/validate/6752c48264746a7ee191ca0c

### Terminer un questionnaire ESG
PATCH http://localhost:8080/questionnaires/finish/6752c48264746a7ee191ca0c
