### add template questionnaire in DB
GET http://localhost:8080/api/addInDB

### Créer un nouveau client
POST http://localhost:8080/clients/register
Content-Type: application/json

{
  "prenom": "Jean",
  "nom": "Dupont",
  "email": "jean.dupont@example.com",
  "fonction": "CEO",
  "nomEntreprise": "Dupont Entreprises",
  "numEntreprise": "123456789",
  "formeJuridique": "SA",
  "adresseSiegeSocial": "123 Rue Principale, 1000 Bruxelles",
  "adresseSiteWeb": "https://dupont-entreprises.com",
  "codeNaceActivitePrincipale": "6201",
  "dernierChiffreDAffaire": 1500000.75,
  "estFranchise": false,
  "nbTravailleur": 50,
  "estDansUnLitige": false,
  "demandeDeLabel": true,
  "partenaire": "Banque Centrale",
  "commentaire": "Client VIP",
  "password": "password123"
}

### Créer un nouveau client (invalide)
POST http://localhost:8080/clients/register
Content-Type: application/json

{
  "prenom": "Sophie",
  "nom": "Martin",
  "email": "sophie.martin@example.com",
  "fonction": "Directrice Marketing",
  "nomEntreprise": "Martin & Co",
  "numEntreprise": "987654321",
  "formeJuridique": "SRL",
  "adresseSiegeSocial": "456 Avenue du Commerce, 7500 Tournai",
  "adresseSiteWeb": "https://martin-co.be",
  "codeNaceActivitePrincipale": "7311",
  "dernierChiffreDAffaire": 250000.50,
  "estFranchise": true,
  "nbTravailleur": 20,
  "estDansUnLitige": true,
  "demandeDeLabel": false,
  "partenaire": "Agence Publicitaire X",
  "commentaire": "En attente de validation du partenariat",
  "password": "securePass2024!"
}


### connecter client (valide)
POST http://localhost:8080/clients/login
Content-Type: application/json

{
  "email": "sophie.martin@example.com",
  "password": "securePass2024!"
}

### connecter Consultant (valide)
POST http://localhost:8080/consultants/login
Content-Type: application/json

{
  "email": "simon.bosseler@vinci.be",
  "password": "password123"
}

### créer un questionnaire ESG pour un client
POST http://localhost:8080/questionnaires/create/questionnaireESG
Content-Type: application/json

{
  "idClient": "67598e8a07e4b818cbdd9cc2"
}

### Récupérer tous les clients
GET http://localhost:8080/clients/All

### Récupérer un seul client par son id
GET http://localhost:8080/clients/getOne/6751b25c0b15056747f31f26

### Récupérer un seul client par son id
GET http://localhost:8080/questionnaires/6752e868faa3e31b8f1a4b45

### Valider un questionnaire ESG
PATCH http://localhost:8080/questionnaires/validate/6759a815e9252921485809c3

### Terminer un questionnaire ESG
PATCH http://localhost:8080/questionnaires/finish/6759a815e9252921485809c3

### Sélectionner une réponse dans une question (ID de la question en paramètre)
PATCH http://localhost:8080/reponses/editReponse
Content-Type: application/json

{
  "idReponse": "6759a815e9252921485809f9",
  "selectionne": true,
  "engage": false
}

### récupérer un questionnaire en fonction de son id
GET http://localhost:8080/questionnaires/IdQuestionnaire/6759a20c8607456ca67694f0

### récupérer un questionnaire en fonction de l'id du client
GET http://localhost:8080/questionnaires/67598e8a07e4b818cbdd9cc2

### Modifier les commentaires d'une question
PATCH http://localhost:8080/questions/editComment
Content-Type: application/json

{
  "idQuestion": "6756c4d38aa8732c1218d6cf",
  "commentaire": "Commentaire modifié"
}

### Récupérer toutes les questions les plus posées
GET http://localhost:8080/questionsPlusPose/getAll

### Créer une question des plus posées
POST http://localhost:8080/questionsPlusPose/add
Content-Type: application/json

{
  "intitule" : "Comment contacter les admins ?",
  "reponse": "via le numero de téléphone"
}


### adad
GET http://localhost:8080/questionnaires/pourcentage/675992588207475dcdecb62d
